### PR TITLE
Update USI_NF_Mode.cfg

### PR DESCRIPTION
**Pull request by cordery**
Correcting typo's.

### CODE REVIEW

**Comment by cordery** [comment]
Perhaps it wasn't a typo, now I see it persists across all the configs and is the name of the actual variable in ThermalNozzleController.cs.   Apologies trying to figure out why my 5m Lightbulb only produces 21kn of thrust.  (I have USI And Near future Electrics)

**Comment by sswelm** [comment]
its a persistant type which I never bother correcting. but 21 kn for a 5m Lightbulp indeed sounds to litle, what is it internal reactor power?

**Comment by cordery** [comment]
image

**Comment by sswelm** [comment]
Alright, and what tech nodes have you unlocked?

**Comment by cordery** [comment]
Thank you for helping out, I've been struggling with this for a while.   I've unlocked the gas core upgrade from Improved Nuclear, High Powered Nuclear, Experimental Nuclear, and Exotic Nuclear Propulsion.  I also have the thermal turbojet/ramjet upgrades from Supersonic Flight, High Altitude Flight, Hypersonic Flight, Aerospace Tech, and Experimental Aircraft Engines.   Not sure what else to look for.

image

**Comment by sswelm** [comment]
Alright, you have all tech nods and your reactor has the correct output power of 320 MW. The only thing that might screw up final trust is the powerTrustMultiplier which is currently missing in the ThermalNozzleController in the LightBulp.cfg

What you could to fix the problem is adding the following to ThermalNozzleController in LightBulp.cfg (located WarpPlugin\Parts\Engines\LightBulb)

	powerTrustMultiplier = 1
	powerTrustMultiplierJet = 1

**Comment by sswelm** [comment]
Thrust is defiantly too low, it should have been exactly 100 times more.

**Comment by sswelm** [comment]
My proposed fixed does appear to fix the problem. I'm going to release this weekend with the fix. Thanks for reporting!

**Comment by cordery** [comment]
Yeah I was wondering why it exploded 30s after ignition, thus the
superabundance of radiators haha.  Thanks again for looking into this!

**Pull request closed without merging**
