### PR TITLE
Patch 231

### PR DESCRIPTION
**Pull request by Sooll3**
Continue file localization and structuring. Fixed a few typos. Adopted a common name for the company: "Kerb Kastria Inc.", because in some places it is also written "Kerb Kastra Inc".

### CODE REVIEW

**Comment by sswelm** [comment]
where are the changes to the localized files?

**Comment by Sooll3** [comment]
After I finish with the parts so soon and will post localization files (en-us and ru). Sometimes I have to change the localization files I have already created, so I do not see the point of ten times editing them in view of minor changes. I think by the end of this week I will finish with localization of parts.

**Comment by sswelm** [comment]
I understand you want to be efficient but because we were working directly on the Master and don't have a Development branch, it limits my options of making a release last weekend and this week.

**Comment by Sooll3** [comment]
Good. I will lay out a localization file today, but I ask to postpone release of updating till the weekend, I think I will manage to finish until the end of part.


>Вторник, 14 мая 2019, 11:03 +03:00 от sswelm <notifications@github.com>:
>
>I understand you want to be efficient but because we were working directly on the Master and don't have a Development branch, it limits my options of making a release last weekend and this week.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Lexa Gjof

**Pull request merged**
