### PR TITLE
Update WarpDrive.cfg

### PR DESCRIPTION
**Pull request by Sooll3**
The continuation of containment and structuring.

### CODE REVIEW

**Comment by georgethejournalist** [comment]
Hi, Sooll3,

thank you for the contribution to this repo, I'm sure everyone is very happy about them. 

I have only one small nitpicky thing - could you perhaps use a merge request after you're done with your changes AND for several commits and files at once? Especially if they are all about the same thing (e.g. updating parts' cfg files).

I'm following this repo and my email is totally swamped with pull requests :)

Thanks for understanding.

**Comment by Sooll3** [comment]
Prompt how to make it and I will make.

**Comment by georgethejournalist** [comment]
Well, ok! I don't know how well versed in git you are, so forgive me if I'm over-explaining, but essentially you can keep your forked repository up to date with sswelm's, do your changes in your repo (commit to your repo as you would normally) and then when you are satisfied with your work, create a pull request to sswelm's repo. This should result in one merge request with the changes you have in your repository but sswelm doesn't.

So:

You need to first make sure your forked repository is kept up to date with sswelm's (so called upstream) repo but that's not difficult at all (see [this github help that explains that)](https://help.github.com/en/articles/merging-an-upstream-repository-into-your-fork).

After that, work with your forked repo. Commit your changes to your fork.

Afterwards, create a pull request from the fork to the upstream. See [yet another github help page that explains this part of the process](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork).

And that's it!

**Comment by Sooll3** [comment]
Very grateful for the explanations, it remains to understand!)

**Comment by georgethejournalist** [comment]
I'm glad I could help! :) I can already see from your other pull requests that you've understood the explanation :) Keep up the good work!

**Comment by Sooll3** [comment]
The desire and help of colleagues in the case work wonders)))

**Pull request merged**
