### PR TITLE
en-us.cfg

### PR DESCRIPTION
**Pull request by Sooll3**
Create a localization file and make appropriate edits to the parts.

### CODE REVIEW

**Comment by sswelm** [comment]
Quite impressive work. But try to combine them in a single pull request if possible

**Comment by Sooll3** [comment]
Regarding the localization of fashion "PhotonSail". There were no changes to the file "part" in the folder "Dipole Drive". For the localizations themselves, you need to create a folder "Localization" and put the files "en-us.cfg" and "ru.cfg" (he could not create it on github.com). There are also localized mod files from the build ("en-us.cfg" and "ru.cfg"): 
1. Hide Empty Tech Tree Nodes; 
2. Interstellar Hybrid Rocketry; 
3. InterstellarFuelSwitch; 
4. WarpPlugin. 
Maybe I can get them to throw in the mail archive, but not change on the resource (github.com) Especially for huge mods such as "InterstellarFuelSwitch" and "WarpPlugin"?

**Comment by sswelm** [comment]
mm, I not sure what we exactly did wrong but some how I can no longer retrieve the Repositry on my machine.

**Comment by sswelm** [comment]
I'm getting fatal error: cannot create directory at "GameDta/PhotonSail"

**Comment by sswelm** [comment]
Spasibo, I think I fixed the problem

**Comment by Sooll3** [comment]
Hi! In fashion "InterstellarFuelSwitch" along the way "KSP-Interstellar-Extended/GameData/InterstellarFuelSwitch/Localization/" create a folder "Resources" and put "en-us.cfg" and "ru.cfg". Because these files contain only the localization of resources that are used in the fashion.

>

**Comment by sswelm** [comment]
Good suggestion, done

**Comment by Sooll3** [comment]
Today I tried to deal with the localization of the file: "Interstellar.dll" (localization is located at:"KSP-Interstellar-Extended/GameData/WarpPlugin/Localization/Fields/". 
As a result, I generally confused what is happening in it, and how to localize it. Lines that do not have references to localization, the abbreviation of the "C" system, also does not have references to localization. Or do not understand something or your localized version of hopelessly outdated? 
Indicators "maximumAllowedWarpThrotle, maximumWarpForAltitude, maximumWarpForGravityPull, warp Engine Throttle" have the abbreviation "guiUnits="c" - what is this designation?  
Is it possible to improve the situation with the localization of this file (add links to external localization files)?

**Comment by sswelm** [comment]
Well is you want to know what translation keys are available, or where they are used, you need to open them the source file. For instance, warp related files can bee found at [here](url=https://github.com/sswelm/KSP-Interstellar-Extended/blob/master/FNPlugin/Propulsion/AlcubierreDrive.cs). I  have only partially given all fields a translation.

**Comment by Sooll3** [comment]
Looking through the code in the "IL" and therefore completely confused. 
I do not know if you are familiar with the mod "KSPDev" - allows you to automatically localize the mod (make and replace the string links). The localization file created by this mod has more than 1400 lines, while the existing localization has less than 300 lines. Significant difference. 
Is it possible to provide a full translation of this file "Interstellar.dll" (localization of external files "cfg"), because this is the only thing that prevents to issue a full localization of fashion in any language (except English)?

**Pull request merged**
