### PR TITLE
Adjust fuel-oxidiser mixture ratios in tanks and engines

### LINKED ISSUE #534: KeroLox IFS ratio
I think I will resolve this quickly, but I still want to bring this into issue to make sure my calculation is correct. This is in preparation for https://github.com/tomasbrod/Interstellar/issues/1 .
Mass ratio for Kerolox as listed on wikipedia is 2.58 - 2.77.
The game unit is volumetric, so we need to divide by density.
2261.17 1219.51
Normalizing that to fraction gives:
0.64963 : 0.35037
0.66563 : 0.33437
The F-1 engine burns kerolox at r=2.27, converted to volume and normalized gives:
0.61997 : 0.38003

Neither of which is close to the 0.4564596 lox fraction of CDT. If no more data suggesting otherwise is found, I propose to set the tank volume ratio to approximately 0.65:0.35.

Are there any mod engines using Kerolox currently?

### PR DESCRIPTION
**Pull request by tomasbrod**
I calculated this using mixture data from [wikipedia](https://en.wikipedia.org/wiki/Liquid_rocket_propellant) and densities from [CommonResources.cfg](https://github.com/sswelm/KSP-Interstellar-Extended/blob/84d5e5b80e3e675448b55b53282d9804b2cac625/GameData/CommunityResourcePack/CommonResources.cfg).
Closes #534

### CODE REVIEW

**Comment by sswelm** [comment]
THe Dudrolox ratios are based on the ratios used in KSPIE Thermal Engines. Changing this would inroduce a big problem for any existing user. Instead I propose we make a new "RO Hydrolox" configuration.

**Comment by tomasbrod** [comment]
@sswelm Is the issue only with Hydrolox or also with Methalox?
Note that I have modified the engines and lantr propellant config as well, to match the tanks. I suppose this could mess with their ISP and also mess up crafts in-flight.
What were the original ratios based on?
Since no engine in kspie uses Kerolox, can I create new PR where only kerolox is changed?
What about ratios in the MethaneEngine (D-1)?

**Comment by sswelm** [comment]
In that case you forgot about the main config file which controls the actual ratio used in the thermal engines, the ones you change are just for shoe. All thermal propellant ratios is configured in EnginePropellants.cfg .Because I don't want to break, for now, please make separate configs.

**Comment by tomasbrod** [comment]
Yes, I am going to make separate pr for just kerolox, to not affect existing engines.
But I still quite not understand quite what you mean. I updated the EnginePropellants file too! What is exactly the problem, so I can find a best solution to it?

**Comment by sswelm** [comment]
I still do not understand why the fuel ratios have to change, as the Oxidizer FUel ratio is kind of abritary. Just look at historical examples and you notice its all over the place and there is no single standard https://en.wikipedia.org/wiki/Comparison_of_orbital_rocket_engines   I recall the 0.8 to 0.2 was mainly chosen for convenience. So unless there is an idea where there is a problem with the ratios not matching up the engines used, there is no need valid change.

**Comment by tomasbrod** [comment]
I agree that the hydrolox ratio does not need to change.

**Pull request closed without merging**
