### PR TITLE
Patch 251

### PR DESCRIPTION
**Pull request by Sooll3**

### CODE REVIEW

**Comment by sswelm** [comment]
Have you verified the sphere tank still works?

**Comment by sswelm** [comment]
Notice Names the reference to the actualy resource, cannot be localized, the are a direct reference to a resource. instead the partmodule use use localized

**Comment by Sooll3** [comment]
Sure it does. I always check the results of applied changes in the game itself.

**Comment by Sooll3** [comment]
It turns out that the parameter "resourceName" can not be localized? And the resources will be in English? Is it possible to apply the displayName parameter to them and still localize them? I would like to get a fully localized interface mod.


>Среда, 18 сентября 2019, 11:02 +03:00 от FreeThinker <notifications@github.com>:
>
>Notice Names the reference to the actualy resource, cannot be localized, the are a direct reference to a resource. instead the partmodule use use localized
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Lexa Gjof

**Comment by sswelm** [comment]
Yes, I would like that as well, I will add some modification to the code before it does that, which should allow you to localize it.

**Comment by Sooll3** [comment]
Great news! However, some parts, I could not find and localize the parameter "resourceName", it is simply missing in the configuration files. As I understand, it is in the file "Patches" "IFSISTGmodular" and similar, but failed to understand them. There are similar parts in "WarpPlugin".


>Среда, 18 сентября 2019, 16:26 +03:00 от FreeThinker <notifications@github.com>:
>
>Yes, I would like that as well, I will add some modification to the code before it does that, which should allow you to localize it.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Lexa Gjof

**Comment by sswelm** [comment]
resourceName means the name of the resource defined by the resource definitions, which cannot be localized. Only the display name and abbreviation can be localized.

**Comment by sswelm** [comment]
I have verified and currently, only the field resourceGui and tankSwitchNames are localizable, meaning you can give a Semicolonseperated of localization string. For example: #LOC_KSPIE_Hydrates_DisplayName;#LOC_KSPIE_Gypsum_DisplayName;#LOC_KSPIE_Lead_DisplayName

**Comment by Sooll3** [comment]
Okay, I'll fix it and see what happens. 
Question on emission spectra: parameter "bandwidthName" can be localized? I localized it and it is correctly displayed on the display.


>Среда, 18 сентября 2019, 19:55 +03:00 от FreeThinker <notifications@github.com>:
>
>I have verified and currently, only the field resourceGui and tankSwitchNames are localizable, meaning you can give a Semicolonseperated of localization string. For example: #LOC_KSPIE_Hydrates_DisplayName;#LOC_KSPIE_Gypsum_DisplayName;#LOC_KSPIE_Lead_DisplayName
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Lexa Gjof

**Comment by Sooll3** [comment]
Not know, as with you contact directly, so write here. 
Part of the "DT-R-QS-1 Quantum Singularity Reactor" - in the menu "Integrated Charged Particles Power Generator" parameter "upgradeTechnologies" - written by: DirectConverterUpgradeA - not happening localization technologies with other technologies in the list all is well.
Some parts in the parameter "Mk1 technode" - present tag-free localization (from the original) "#autoLOC_501020", such as "DT-R-QS-1 Quantum Singularity Reactor".


>Среда, 18 сентября 2019, 19:55 +03:00 от FreeThinker <notifications@github.com>:
>
>I have verified and currently, only the field resourceGui and tankSwitchNames are localizable, meaning you can give a Semicolonseperated of localization string. For example: #LOC_KSPIE_Hydrates_DisplayName;#LOC_KSPIE_Gypsum_DisplayName;#LOC_KSPIE_Lead_DisplayName
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Lexa Gjof

**Comment by sswelm** [comment]
I think you want to localize the tech listed under upgradeTechnologies right? Notice it uses a custom pre-processing step which runs before localization is active. Currently, it only has support for us-en, but I need to add support for multi language

**Comment by Sooll3** [comment]
About (upgradeTechnologies), the game picks up localization from fashion "CTT" or the equivalent in "KSPI-E" (and is checked). The tag appears only in some parts (not all) and it is in the parameter "Mk1 technode" (only in it, with Mk2 and Mk3 everything is normal) this does not happen. 
About "DirectEnergyConverterUpgradeA" - the error somewhere has crept into the code since the details of the "LargeElectricGenerator" there is no technology "A", but only "B", "C" and "D". I don't really understand, as part of the "LargeElectricGenerator" can be associated with the "QuantumSingularityReactor2". 
Can you show in the screenshots (forum.kerbalspaceprogram.com), to eliminate the confusion?


>Четверг, 19 сентября 2019, 13:38 +03:00 от FreeThinker <notifications@github.com>:
>
>I think you want to localize the tech listed under upgradeTechnologies right? Notice it uses a custom pre-processing step which runs before localization is active. Currently, it only has support for us-en, but I need to add support for multi language
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Lexa Gjof

**Pull request closed without merging**
